### ISSUE TITLE
Bug: KeyError: 'centroid_lat'

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#193]
**Describe the bug**
```
Traceback (most recent call last):
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'centroid_lat'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py", line 218, in <module>
    main()
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py", line 203, in main
    datamodule = get_data_module()
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py", line 162, in get_data_module
    data_module.prepare_data()
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/pytorch_lightning/core/datamodule.py", line 428, in wrapped_fn
    fn(*args, **kwargs)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/dataset/datamodule.py", line 146, in prepare_data
    self.gsp_data_source = GSPDataSource(
  File "<string>", line 14, in __init__
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/gsp/gsp_data_source.py", line 69, in __post_init__
    self.load()
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/gsp/gsp_data_source.py", line 84, in load
    lat=self.metadata["centroid_lat"], lon=self.metadata["centroid_lon"]
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/geopandas/geodataframe.py", line 1299, in __getitem__
    result = super(GeoDataFrame, self).__getitem__(key)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'centroid_lat'
```

**To Reproduce**
Running `prepare_ml_data.py` on `leonardo`

**Things I've tried to fix it**
I tried changing `centroid_lat` to `cen_lat` in `gsp_data_source.py` but that didn't help :(

**Comment by peterdudfield** [comment]
Any chance there are the logs before the error hits? in debug mode? That'll help a little bit

**Comment by JackKelly** [comment]
Sure, here's the log after I changed `centroid_{lat,lon}` to `cen_{lat,lon}`:

```
[?2004h(nowcasting_dataset) [01;32mjack@leonardo[00m:[01;34m~/dev/ocf/nowcasting_dataset/scripts[00m$ /.[K[K./prepare_ml_data.py 
[?2004l
2021-10-04 08:08:31,779 INFO /home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py 96 Checking if all paths exist...
2021-10-04 08:08:32,036 INFO /home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py 112 Success!  All paths exist!
2021-10-04 08:08:32,106 INFO /home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py 161 prepare_data()
15 bad PV systems found and removed!
pv_power = 400.0 MB
/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
Traceback (most recent call last):
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'cen_lat'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py", line 218, in <module>
    main()
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py", line 203, in main
    datamodule = get_data_module()
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py", line 162, in get_data_module
    data_module.prepare_data()
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/pytorch_lightning/core/datamodule.py", line 428, in wrapped_fn
    fn(*args, **kwargs)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/dataset/datamodule.py", line 146, in prepare_data
    self.gsp_data_source = GSPDataSource(
  File "<string>", line 14, in __init__
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/gsp/gsp_data_source.py", line 69, in __post_init__
    self.load()
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/gsp/gsp_data_source.py", line 84, in load
    lat=self.metadata["cen_lat"], lon=self.metadata["cen_lon"]
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/geopandas/geodataframe.py", line 1299, in __getitem__
    result = super(GeoDataFrame, self).__getitem__(key)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'cen_lat'
[?2004h(nowcasting_dataset) [01;32mjack@leonardo[00m:[01;34m~/dev/ocf/nowcasting_dataset/scripts[00m$ 
```

**Comment by peterdudfield** [comment]
oh I might know what it is - can you delete the local file gsp_shape. It should be in the 'data_sources/gsp' folder. Then try it again?

**Comment by peterdudfield** [comment]
if that doesnt work, could you cahgne the logging to debug, and I should be able to help more

**Comment by JackKelly** [comment]
Sure, thanks, I'll give that a go!
These files exist in the `data_sources/gsp/gsp_shape` folder:

gsp_shape.cpg  gsp_shape.dbf  gsp_shape.prj  gsp_shape.shp  gsp_shape.shx


Should I delete all of them?

**Comment by peterdudfield** [comment]
yea delete them, they will reappear next time you run things, and hopefully with that variable

**Comment by JackKelly** [comment]
Nice, yup, I deleted the whole `data_sources/gsp/gsp_shape` folder and it seems to be running nicely now!  Thanks!

In the future, is there any way to automatically check if the `data_sources/gsp/gsp_shape` folder should be deleted?  If not, it's probably sufficient to write some documentation somewhere on how to delete `nowcasting_dataset` 'cache' of files.

**Comment by peterdudfield** [comment]
Yea - its only if the data structure changes of that object. Could always add a try statement, and if it fails, force a new download, - or something like that

**Comment by JackKelly** [comment]
that sounds like a good plan :)

**Comment by JackKelly** [comment]
The original issue is fixed now.  I've started a new issue to discuss automatically re-downloading the `gsp_shape` folder: #201
