### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 14455) exited unexpectedly

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#194]
**Describe the bug**
This exception occured whilst running `prepare_ml_data.py` on `leonardo`, using `num_workers=8`.

Using git branch `origin/jack/read-from-native-eumetsat-files`, commit ID `8c6f17327eb816bfea188337e4662d0e25442833`

TBH, I think this traceback is pretty useless, so I don't have much hope that we'll be able to figure out what went wrong!  It's possible the machine ran out of RAM, but I wasn't logging RAM usage...

```
2021-10-04 08:51:51,053 INFO /home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py 178 Got batch 23415
2021-10-04 08:51:56,982 INFO /home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py 178 Got batch 23416
2021-10-04 08:52:01,352 INFO /home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py 178 Got batch 23417
2021-10-04 08:52:05,158 INFO /home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py 178 Got batch 23418
2021-10-04 08:52:10,258 INFO /home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py 178 Got batch 23419
2021-10-04 08:52:14,906 INFO /home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py 178 Got batch 23420
2021-10-04 08:52:19,657 INFO /home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py 178 Got batch 23421
2021-10-04 08:52:23,530 INFO /home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py 178 Got batch 23422
Traceback (most recent call last):
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 14455) is killed by signal: Killed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py", line 218, in <module>
    main()
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py", line 207, in main
    iterate_over_dataloader_and_write_to_disk(datamodule.train_dataloader(), DST_TRAIN_PATH)
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/./prepare_ml_data.py", line 177, in iterate_over_dataloader_and_write_to_disk
    for batch_i, batch in enumerate(dataloader):
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 14455) exited unexpectedly
```

**Comment by JackKelly** [comment]
Hmm, yeah, I think `leonardo` ran out of RAM... Here's what `htop` looks like when re-running `prepare_ml_data.py` with exactly the same settings (note that it's using all its swap):

![image](https://user-images.githubusercontent.com/460756/135825967-c97ac30e-387b-4132-85a4-4026963cbdaf.png)

I'll try reducing `num_workers` to 4...

**Comment by JackKelly** [comment]
Yeah, memory usage looks a lot more comfortable when only using `num_workers=4`:

![image](https://user-images.githubusercontent.com/460756/135826792-2c5c413e-afb3-432a-a23f-cc1d854d5bdd.png)

I'll buy and install another 64 GB of RAM soon :)

**Comment by JackKelly** [comment]
After running for about an hour with `num_workers=4`, the memory usage still looks comfortable:

![image](https://user-images.githubusercontent.com/460756/135833752-32a9c864-2e7b-403b-aa02-894885ea0692.png)
