### ISSUE TITLE
Code needs to create `output_data.filepath` before attempting to create log files

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#429]
For now, a simple fix is to manually create  `output_data.filepath` before attempting to create log files

Otherwise this happens:

```
(nowcasting_dataset) jack@leonardo:~/dev/ocf/nowcasting_dataset$ scripts/prepare_ml_data.py 
Traceback (most recent call last):
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/prepare_ml_data.py", line 79, in <module>
    main()
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/utils.py", line 155, in inner_func
    return func(*args, **kwargs)
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/prepare_ml_data.py", line 66, in main
    manager.configure_loggers(log_level=log_level, names_of_selected_data_sources=data_source)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py", line 79, in configure_loggers
    logging.FileHandler(combined_log_filename, mode="a"),
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/storage_ssd_4tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v12_testing/combined.log'
```

**Comment by peterdudfield** [comment]
I can have a go at this

**Comment by JackKelly** [comment]
awesome, thank you!
