### ISSUE TITLE
FileNotFoundError: ...EUMETSAT/SEVIRI_RSS/zarr/v2/eumetsat_zarr_* does not exist!

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#430]
When running `prepare_ml_data.py` just now on `leonardo`....

```
2021-11-17 17:27:41,169 DEBUG processID=1551253 Creating satellite DataSource object. | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py#L103
DEBUG:nowcasting_dataset.manager:Creating satellite DataSource object.
2021-11-17 17:27:41,170 ERROR processID=1551253 Exception whilst instantiating satellite! | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py#L119
Traceback (most recent call last):
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py", line 117, in initialise_data_sources
    data_source = data_source_class(**config_for_data_source)
  File "<string>", line 8, in __init__
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/satellite/satellite_data_source.py", line 30, in __post_init__
    super().__post_init__(image_size_pixels, meters_per_pixel)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py", line 373, in __post_init__
    super().__post_init__(image_size_pixels, meters_per_pixel)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py", line 345, in __post_init__
    super().__post_init__()
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py", line 51, in __post_init__
    self.check_input_paths_exist()
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py", line 378, in check_input_paths_exist
    nd_fs_utils.check_path_exists(self.zarr_path)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/filesystem/utils.py", line 98, in check_path_exists
    raise FileNotFoundError(f"{path} does not exist!")
FileNotFoundError: /mnt/storage_ssd_8tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/satellite/EUMETSAT/SEVIRI_RSS/zarr/v2/eumetsat_zarr_* does not exist!
ERROR:nowcasting_dataset.manager:Exception whilst instantiating satellite!
Traceback (most recent call last):
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py", line 117, in initialise_data_sources
    data_source = data_source_class(**config_for_data_source)
  File "<string>", line 8, in __init__
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/satellite/satellite_data_source.py", line 30, in __post_init__
    super().__post_init__(image_size_pixels, meters_per_pixel)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py", line 373, in __post_init__
    super().__post_init__(image_size_pixels, meters_per_pixel)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py", line 345, in __post_init__
    super().__post_init__()
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py", line 51, in __post_init__
    self.check_input_paths_exist()
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py", line 378, in check_input_paths_exist
    nd_fs_utils.check_path_exists(self.zarr_path)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/filesystem/utils.py", line 98, in check_path_exists
    raise FileNotFoundError(f"{path} does not exist!")
FileNotFoundError: /mnt/storage_ssd_8tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/satellite/EUMETSAT/SEVIRI_RSS/zarr/v2/eumetsat_zarr_* does not exist!
Traceback (most recent call last):
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/prepare_ml_data.py", line 79, in <module>
    main()
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/utils.py", line 155, in inner_func
    return func(*args, **kwargs)
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/prepare_ml_data.py", line 67, in main
    manager.initialise_data_sources(names_of_selected_data_sources=data_source)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py", line 117, in initialise_data_sources
    data_source = data_source_class(**config_for_data_source)
  File "<string>", line 8, in __init__
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/satellite/satellite_data_source.py", line 30, in __post_init__
    super().__post_init__(image_size_pixels, meters_per_pixel)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py", line 373, in __post_init__
    super().__post_init__(image_size_pixels, meters_per_pixel)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py", line 345, in __post_init__
    super().__post_init__()
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py", line 51, in __post_init__
    self.check_input_paths_exist()
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py", line 378, in check_input_paths_exist
    nd_fs_utils.check_path_exists(self.zarr_path)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/filesystem/utils.py", line 98, in check_path_exists
    raise FileNotFoundError(f"{path} does not exist!")
FileNotFoundError: /mnt/storage_ssd_8tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/satellite/EUMETSAT/SEVIRI_RSS/zarr/v2/eumetsat_zarr_* does not exist!
```

**Comment by JackKelly** [comment]
it's my code in Manager which is complaining!  It tries to check that all the input directories exist... and it doesn't know what to do with a wildcard... I'll fix that now!
