### ISSUE TITLE
Worker process satellite raised exception! Example is wrong shape!

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#439]
```
2021-11-18 09:07:37,860 DEBUG processID=1584660 SatelliteDataSource creating batch 1! | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py#L200
DEBUG:nowcasting_dataset.data_sources.data_source:SatelliteDataSource creating batch 1!
2021-11-18 09:07:38,377 WARNING processID=1584661 Satellite Zarr has 13 duplicated times.  Fixing... | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/satellite/satellite_data_source.py#L265
WARNING:nowcasting_dataset:Satellite Zarr has 13 duplicated times.  Fixing...
2021-11-18 09:07:41,600 DEBUG processID=1584661 HRVSatelliteDataSource creating batch 1! | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py#L200
DEBUG:nowcasting_dataset.data_sources.data_source:HRVSatelliteDataSource creating batch 1!
2021-11-18 09:07:51,797 ERROR processID=1583863 Worker process satellite raised exception!
Example is wrong shape! x_meters_center=507636.659094526
y_meters_center=197928.89001960697
t0_dt=2018-03-19 07:40:00
times are <xarray.DataArray 'time' (time: 0)>
array([], dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 
expected shape=(31, 24, 24, 11)
actual shape (0, 24, 24, 11) | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py#L457
NoneType: None
ERROR:nowcasting_dataset.manager:Worker process satellite raised exception!
Example is wrong shape! x_meters_center=507636.659094526
y_meters_center=197928.89001960697
t0_dt=2018-03-19 07:40:00
times are <xarray.DataArray 'time' (time: 0)>
array([], dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 
expected shape=(31, 24, 24, 11)
actual shape (0, 24, 24, 11)
NoneType: None
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py", line 203, in create_batches
    batch = self.get_batch(
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py", line 261, in get_batch
    examples = [future_example.result() for future_example in future_examples]
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/data_source.py", line 261, in <listcomp>
    examples = [future_example.result() for future_example in future_examples]
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/satellite/satellite_data_source.py", line 130, in get_example
    raise RuntimeError(
RuntimeError: Example is wrong shape! x_meters_center=507636.659094526
y_meters_center=197928.89001960697
t0_dt=2018-03-19 07:40:00
times are <xarray.DataArray 'time' (time: 0)>
array([], dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 
expected shape=(31, 24, 24, 11)
actual shape (0, 24, 24, 11)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/prepare_ml_data.py", line 79, in <module>
    main()
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/utils.py", line 155, in inner_func
    return func(*args, **kwargs)
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/prepare_ml_data.py", line 72, in main
    manager.create_batches(overwrite_batches)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py", line 460, in create_batches
    raise exception
RuntimeError: Example is wrong shape! x_meters_center=507636.659094526
y_meters_center=197928.89001960697
t0_dt=2018-03-19 07:40:00
times are <xarray.DataArray 'time' (time: 0)>
array([], dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 
expected shape=(31, 24, 24, 11)
actual shape (0, 24, 24, 11)
```

**Comment by jacobbieker** [comment]
It seems the t0_dt is in 2018, satellite data only exists for 2020-2021

**Comment by JackKelly** [comment]
Ah!  Good catch!  OK, I can look into that... that's probably the code I wrote which is _supposed_ to find the intersection of the datetimes between all the data sources!  I'll have a poke around now!

**Comment by JackKelly** [comment]
Huh, yeah, `train/spatial_and_temporal_locations_of_each_example.csv` clearly uses datetimes which aren't in the satellite dataset:

```
$ head /mnt/storage_ssd_4tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v11/train/spatial_and_temporal_locations_of_each_example.csv 
,t0_datetime_UTC,x_center_OSGB,y_center_OSGB
0,2016-07-10 15:30:00,248367.51880896094,660349.0939485433
1,2019-07-20 05:00:00,321091.0215170703,677350.2381857462
2,2021-07-12 08:05:00,254579.95994972216,667108.4323026732
```

I think this might be because I tried running `prepare_ml_data.py` with a subset of the data sources... let me try in a fresh target directory....

**Comment by JackKelly** [comment]
Yeah, with a fresh target directory, it looks like the code is now doing the right thing...

```
2021-11-18 09:36:47,321 DEBUG processID=1585090 Getting t0 time periods for gsp | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py#L246
DEBUG:nowcasting_dataset.manager:Getting t0 time periods for gsp
2021-11-18 09:36:47,323 DEBUG processID=1585090 Getting t0 time periods for topographic | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py#L246
DEBUG:nowcasting_dataset.manager:Getting t0 time periods for topographic
2021-11-18 09:36:47,323 DEBUG processID=1585090 Skipping topographic because it has not concept of datetime. | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py#L251
DEBUG:nowcasting_dataset.manager:Skipping topographic because it has not concept of datetime.
2021-11-18 09:36:47,323 DEBUG processID=1585090 Getting t0 time periods for sun | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py#L246
DEBUG:nowcasting_dataset.manager:Getting t0 time periods for sun
2021-11-18 09:36:48,199 DEBUG processID=1585090 Will be dropping 63007 datetimes out of 105121 as elevation is < 10 | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/sun/sun_data_source.py#L119
DEBUG:nowcasting_dataset.data_sources.sun.sun_data_source:Will be dropping 63007 datetimes out of 105121 as elevation is < 10
2021-11-18 09:36:53,271 DEBUG processID=1585090 Found 52,396 datetimes at freq=`0 days 00:05:00` across DataSources=['pv', 'satellite', 'hrvsatellite', 'nwp', 'gsp', 'topographic', 'sun'].  From 2020-01-01 10:20:00 to 2021-09-30 14:30:00. | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py#L262
DEBUG:nowcasting_dataset.manager:Found 52,396 datetimes at freq=`0 days 00:05:00` across DataSources=['pv', 'satellite', 'hrvsatellite', 'nwp', 'gsp', 'topographic', 'sun'].  From 2020-01-01 10:20:00 to 2021-09-30 14:30:00.
2021-11-18 09:36:53,271 INFO processID=1585090 Splitting data with method SplitMethod.DAY_RANDOM_TEST_DATE | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/dataset/split/split.py#L73
INFO:nowcasting_dataset.dataset.split.split:Splitting data with method SplitMethod.DAY_RANDOM_TEST_DATE
2021-11-18 09:36:53,283 DEBUG processID=1585090 Split data done! | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/dataset/split/split.py#L201
DEBUG:nowcasting_dataset.dataset.split.split:Split data done!
2021-11-18 09:36:53,283 DEBUG processID=1585090 train has 28,452 datetimes, from 2020-01-01 10:20:00 to 2020-12-31 12:15:00 | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/dataset/split/split.py#L207
DEBUG:nowcasting_dataset.dataset.split.split:train has 28,452 datetimes, from 2020-01-01 10:20:00 to 2020-12-31 12:15:00
2021-11-18 09:36:53,283 WARNING processID=1585090 validation has 0 datetimes | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/dataset/split/split.py#L205
WARNING:nowcasting_dataset.dataset.split.split:validation has 0 datetimes
2021-11-18 09:36:53,283 DEBUG processID=1585090 test has 23,944 datetimes, from 2021-01-01 10:20:00 to 2021-09-30 14:30:00 | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/dataset/split/split.py#L207
DEBUG:nowcasting_dataset.dataset.split.split:test has 23,944 datetimes, from 2021-01-01 10:20:00 to 2021-09-30 14:30:00
```

**Comment by JackKelly** [comment]
(but, if this does turn out to be the issue, then the code should produce a more helpful error or warning, so this is easier to debug...)

**Comment by peterdudfield** [comment]
Perhaps it could be part of https://github.com/openclimatefix/nowcasting_dataset/issues/425

If the csv files are already there, then it checks agains the global start and end time

**Comment by JackKelly** [comment]
Good idea!

OK, I think we can close this issue now... Starting with an empty target directory fixed this issue...

Implementing issue #323 (with Peter's suggestion) should fix this for good...  And implementing issue #448 should make this issue easier to debug in the future...
