### ISSUE TITLE
np.random.choice blows up because the validation t0_datetimes is empty (because we don't have a validation set!)

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#442]
I'm working on fixing this now... shouldn't be too hard!

```
DEBUG:nowcasting_dataset.manager:Found 52,396 datetimes at freq=`0 days 00:05:00` across DataSources=['pv', 'satellite', 'hrvsatellite', 'nwp', 'gsp', 'topographic', 'sun'].  From 2020-01-01 10:20:00 to 2021-09-30 14:30:00.
2021-11-18 09:36:53,271 INFO processID=1585090 Splitting data with method SplitMethod.DAY_RANDOM_TEST_DATE | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/dataset/split/split.py#L73
INFO:nowcasting_dataset.dataset.split.split:Splitting data with method SplitMethod.DAY_RANDOM_TEST_DATE
2021-11-18 09:36:53,283 DEBUG processID=1585090 Split data done! | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/dataset/split/split.py#L201
DEBUG:nowcasting_dataset.dataset.split.split:Split data done!
2021-11-18 09:36:53,283 DEBUG processID=1585090 train has 28,452 datetimes, from 2020-01-01 10:20:00 to 2020-12-31 12:15:00 | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/dataset/split/split.py#L207
DEBUG:nowcasting_dataset.dataset.split.split:train has 28,452 datetimes, from 2020-01-01 10:20:00 to 2020-12-31 12:15:00
2021-11-18 09:36:53,283 WARNING processID=1585090 validation has 0 datetimes | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/dataset/split/split.py#L205
WARNING:nowcasting_dataset.dataset.split.split:validation has 0 datetimes
2021-11-18 09:36:53,283 DEBUG processID=1585090 test has 23,944 datetimes, from 2021-01-01 10:20:00 to 2021-09-30 14:30:00 | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/dataset/split/split.py#L207
DEBUG:nowcasting_dataset.dataset.split.split:test has 23,944 datetimes, from 2021-01-01 10:20:00 to 2021-09-30 14:30:00
2021-11-18 09:36:53,283 DEBUG processID=1585090 Creating 250 batches x 32 examples per batch = 8,000 examples for train. | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py#L182
DEBUG:nowcasting_dataset.manager:Creating 250 batches x 32 examples per batch = 8,000 examples for train.
2021-11-18 09:36:53,316 WARNING processID=1585090 There are some nans in the gsp data, so to get x,y locations we have to do a big loop | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/gsp/gsp_data_source.py#L137
WARNING:nowcasting_dataset.data_sources.gsp.gsp_data_source:There are some nans in the gsp data, so to get x,y locations we have to do a big loop
2021-11-18 09:37:47,563 INFO processID=1585090 Making /mnt/storage_ssd_4tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v13_testing/train if it does not exist. | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py#L191
INFO:nowcasting_dataset.manager:Making /mnt/storage_ssd_4tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v13_testing/train if it does not exist.
2021-11-18 09:37:47,564 DEBUG processID=1585090 Writing /mnt/storage_ssd_4tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v13_testing/train/spatial_and_temporal_locations_of_each_example.csv | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py#L193
DEBUG:nowcasting_dataset.manager:Writing /mnt/storage_ssd_4tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v13_testing/train/spatial_and_temporal_locations_of_each_example.csv
2021-11-18 09:37:47,593 DEBUG processID=1585090 Creating 10 batches x 32 examples per batch = 320 examples for validation. | /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py#L182
DEBUG:nowcasting_dataset.manager:Creating 10 batches x 32 examples per batch = 320 examples for validation.
Traceback (most recent call last):
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/prepare_ml_data.py", line 79, in <module>
    main()
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/utils.py", line 155, in inner_func
    return func(*args, **kwargs)
  File "/home/jack/dev/ocf/nowcasting_dataset/scripts/prepare_ml_data.py", line 71, in main
    manager.create_files_specifying_spatial_and_temporal_locations_of_each_example_if_necessary()
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py", line 186, in create_files_specifying_spatial_and_temporal_locations_of_each_example_if_necessary
    df_of_locations = self.sample_spatial_and_temporal_locations_for_examples(
  File "/home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/manager.py", line 287, in sample_spatial_and_temporal_locations_for_examples
    shuffled_t0_datetimes = np.random.choice(t0_datetimes, size=n_examples)
  File "mtrand.pyx", line 915, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
```

**Comment by JackKelly** [comment]
Closing this in favour of #441
