### ISSUE TITLE
Mwooooore CPUs!!!

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#50]

**Comment by JackKelly** [comment]
Urg.  Need to request CPU quota increase from Google Cloud.  Current limit is 24 cores.

**Comment by JackKelly** [comment]
Good news: GCP increased our CPU quota within minutes.

Bad news:  For single-GPU machines, you can't have more than 24 CPUs!  For 64 cores, can have 4 GPUs, but my code doesn't work for multiple GPUs:

```
/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:523: UserWarning: You requested multiple GPUs but did not specify a backend, e.g. `Trainer(accelerator="dp"|"ddp"|"ddp2")`. Setting `accelerator="ddp_spawn"` for you.
  rank_zero_warn(
GPU available: True, used: True
TPU available: False, using: 0 TPU cores

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/jack/miniconda3/envs/nowcasting_dataset/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'LitAutoEncoder' on <module '__main__' (built-in)>
```

**Comment by JackKelly** [comment]
Using 1 GPU on a 64 CPU machine:

* 14.5 it/s after 4,500 it, with 12 workers on 64-core VM, 1 GPU.
* 22.8 it/s with 60 workers, 1 GPU.  Uses about 52 GB of RAM.  Tops out at about 350 MB/s network read speed.  Saturates all the CPU cores.  GPU hovers around 30% - 80% utilisation.
